add admin script to destroy a running app+data container pair

diff --git a/script/functions b/script/functions
--- a/script/functions
+++ b/script/functions
@@ -3,3 +3,8 @@ function smitty() {
   echo -e "[INFO] $@"
   "$@"
 }
+
+function err() {
+  echo "[ERROR] $@" >&2
+  exit 1
+}
